# authorization

# AUTH_FUNZIONALITA = valore permesso
# ex: 
# AUTH_UFFICI = AUTH(UTENTE_LOGGATO) (40)
# OR
# AUTH_UFFICI = 40

AUTH_UFFICI=90
AUTH_EVENTI=90
AUTH_LIVEDEMO=99
AUTH_PROFILO=99
AUTH_LOGIN=91
AUTH_LOGOUT=90
AUTH_MAXPOSTIPRENOTABILI=0

N_POSTIPRENOTABILI=10